// flow-typed signature: a0f3e031fe9bf6f1544f242c60457e51
// flow-typed version: <<STUB>>/babel-plugin-dynamic-import-node-babel-7_v^2.0.7/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-dynamic-import-node-babel-7'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-dynamic-import-node-babel-7' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-dynamic-import-node-babel-7/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-dynamic-import-node-babel-7/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-dynamic-import-node-babel-7/lib/index'>;
}
