// flow-typed signature: 00614a19d342ed062abad0bff107a8da
// flow-typed version: <<STUB>>/universal-rxjs-ajax_v^2.0.1/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'universal-rxjs-ajax'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'universal-rxjs-ajax' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'universal-rxjs-ajax/lib/index' {
  declare module.exports: any;
}

declare module 'universal-rxjs-ajax/src/index' {
  declare module.exports: any;
}

declare module 'universal-rxjs-ajax/tests/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'universal-rxjs-ajax/lib/index.js' {
  declare module.exports: $Exports<'universal-rxjs-ajax/lib/index'>;
}
declare module 'universal-rxjs-ajax/src/index.js' {
  declare module.exports: $Exports<'universal-rxjs-ajax/src/index'>;
}
declare module 'universal-rxjs-ajax/tests/index.test.js' {
  declare module.exports: $Exports<'universal-rxjs-ajax/tests/index.test'>;
}
