// flow-typed signature: f6f8dfd7b773aa8b8f0c67b9b4f9fce3
// flow-typed version: <<STUB>>/@babel/plugin-proposal-throw-expressions_v^7.2.0/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-proposal-throw-expressions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-proposal-throw-expressions' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-proposal-throw-expressions/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-proposal-throw-expressions/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-throw-expressions/lib/index'>;
}
