// flow-typed signature: bd0fa5b354f1a2ae77f8ed082d08b402
// flow-typed version: <<STUB>>/@babel/plugin-proposal-async-generator-functions_v^7.2.0/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-proposal-async-generator-functions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-proposal-async-generator-functions' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-proposal-async-generator-functions/lib/for-await' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-async-generator-functions/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-proposal-async-generator-functions/lib/for-await.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-async-generator-functions/lib/for-await'>;
}
declare module '@babel/plugin-proposal-async-generator-functions/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-async-generator-functions/lib/index'>;
}
